version: "3.7"

services:
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
        - CONF_PATH=${CONF_PATH}
    cap_add:
      - all
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/master/my.cnf:/etc/mysql/my.cnf
    #- ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"

  fpm:
    build:
      context: ../
      dockerfile: ./docker/fpm/Dockerfile
    ports:
      - "${FPM_PORT}:8000"
    #command: php -f /usr/bin/composer.phar install
    volumes:
      - ../data/api:/var/www
      - ./fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      #- ./fpm/xhprof.ini:/usr/local/etc/php/conf.d/xhprof.ini

  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./db:/var/lib/clickhouse
    ulimits:
      nofile: 262144


networks:
  elk:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  mysql:
    driver: local
