ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM  bitnami/elasticsearch:${ELASTIC_VERSION}
#https://mirror.yandex.ru/mirrors/elastic/7/ stable main
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
